name="psedospeaks"

compatibility_date = "2024-03-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets={directory=".worker-next/assets",binding="ASSETS"}

[build]
command = "npm install --no-optional && npm run build"
